version: 2

sources:
  - name: ecommerce
    description: Raw e-commerce data
    schema: staging
    tables:
      - name: customers
        description: Customer information
      - name: products
        description: Product catalog
      - name: orders
        description: Order transactions
